name: Extract File References

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Ruta del archivo de prueba'
        required: true
        default: 'cypress/e2e/Tests/API/Cards/GX3-5811-boardMembers.api.cy.ts'

jobs:
  extract-references:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Step 1 - Read aliases from .aliases.json
      run: |
        echo "Leyendo los alias desde .aliases.json"
        ALIAS_JSON=$(cat .aliases.json)
        echo "$ALIAS_JSON" | grep -o '"@[^"]*":\s*"[^"]*"' | awk -F ': ' '{print $1, $2}' > alias_list.txt
        echo "Alias leídos y almacenados en alias_list.txt"
        
    - name: Show alias list content
      run: |
        echo "Contenido de alias_list.txt:"
        cat alias_list.txt

    - name: Step 2 - Process and resolve paths from import statements
      run: |
        RESOLVED_FILES="cypress/e2e/Tests/API/Cards/GX3-5811-boardMembers.api.cy.ts"
        echo "Ruta posix inicial: $RESOLVED_FILES"
        
        function process_file() {
          local file=$1
          echo "Procesando archivo: $file"
          FILE_REFERENCES=$(grep -Eo 'import\s+.*\s+from\s+["'"'"'][^"'"'"']+["'"'"']' "$file" || echo "")
          echo "Referencias encontradas en el archivo $file:"
          echo "$FILE_REFERENCES"

          while IFS= read -r reference; do
            path=$(echo "$reference" | sed -E 's/.*from\s+["'"'"']([^"'"'"']+)["'"'"'];/\1/')
            echo "Ruta de referencia encontrada: $path"
            
            # Resolver rutas relativas
            if [[ "$path" == .* || "$path" == ..* ]]; then
              resolved_path=$(realpath --relative-to=. "$(dirname "$file")/$path")
              echo "Ruta resuelta (relativa): $resolved_path"
            fi
            
            # Resolver alias
            if [[ "$path" == @* ]]; then
              alias_name=$(echo "$path" | cut -d'/' -f1)
              alias_subpath=$(echo "$path" | sed -E 's|^[^/]+/?||')
              alias_base=$(grep -o "\"$alias_name\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" alias_list.txt | awk -F ': ' '{print $2}' | tr -d '"')
              resolved_path="${alias_base}/$alias_subpath"
              echo "Ruta resuelta (alias): $resolved_path"
            fi
            
            # Eliminar './' al principio de la ruta, si existe
            resolved_path="${resolved_path#./}"
            echo "Ruta final procesada: $resolved_path"
            
            # Filtrar y mostrar solo las rutas relevantes
            if [[ "$resolved_path" == cypress/* ]]; then
              echo "Archivo relevante encontrado: $resolved_path"
              echo "$resolved_path" >> resolved_files.txt
              
              # Llamar a la función recursiva para procesar archivos referenciados
              process_file "$resolved_path"
            fi
            echo "---------"
          done <<< "$FILE_REFERENCES"
        }

        # Iniciar el proceso con el archivo inicial
        process_file "cypress/e2e/Tests/API/Cards/GX3-5811-boardMembers.api.cy.ts"
        
        echo "Archivos relevantes finales:"
        cat resolved_files.txt

