name: Extract File References

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Ruta del archivo de prueba'
        required: true
        default: 'cypress/e2e/Tests/API/Cards/GX3-5811-boardMembers.api.cy.ts'

jobs:
  resolve-aliases:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set the path for the test file
      run: |
        TEST_POSIX="${{ github.event.inputs.test_file }}"
        echo "Ruta del archivo de prueba: $TEST_POSIX"
        if [ ! -f "$TEST_POSIX" ]; then
          echo "No se encontró el archivo de prueba en la ruta especificada: $TEST_POSIX"
          exit 1
        else
          echo "Archivo de prueba encontrado: $TEST_POSIX"
        fi

    - name: Show the contents of the test file (First few lines)
      run: |
        echo "Mostrando las primeras 10 líneas del archivo de prueba $TEST_POSIX:"
        head -n 10 "$TEST_POSIX"

    - name: Extract and resolve alias paths
      run: |
        ESLINT_CONFIG="./.aliases.json"
        echo "Valor de ESLINT_CONFIG: $ESLINT_CONFIG"
        declare -A alias_map

        if [[ ! -f "$ESLINT_CONFIG" ]]; then
          echo "El archivo de configuración de alias no existe: $ESLINT_CONFIG"
          exit 1
        fi

        alias_entries=$(grep -oP '"@[^"]+" *: *"[^"]+"' "$ESLINT_CONFIG" || echo "")
        echo "Alias extraídos del archivo .aliases.json: $alias_entries"

        echo "$alias_entries" | while IFS= read -r line; do
          alias_name=$(echo "$line" | grep -oP '"@[^"]+' | tr -d '"')
          real_path=$(echo "$line" | grep -oP '":\s*"[^"]+"' | sed -E 's/^":\s*"//')
          alias_name_var="ALIAS_${alias_name//@/}"
          alias_map["$alias_name_var"]="$real_path"
        done

        # Exportar alias como variables de entorno utilizando GITHUB_ENV
        for alias in "${!alias_map[@]}"; do
          echo "$alias=${alias_map[$alias]}" >> $GITHUB_ENV
        done
        echo "Alias exportados correctamente"

    - name: Extract file references and resolve paths
      run: |
        echo "Buscando importaciones en el archivo $TEST_POSIX"
        FILE_REFERENCES=$(grep -Eo 'import\s+.*\s+from\s+["'"'"'][^"'"'"']+["'"'"'];' "$TEST_POSIX" || echo "")
        echo "Referencias encontradas: $FILE_REFERENCES"

        if [ -z "$FILE_REFERENCES" ]; then
          echo "No se encontraron referencias de importación en el archivo."
          exit 1
        fi

        RESOLVED_FILES=""
        while IFS= read -r file; do
          echo "Procesando archivo: $file"
          path=$(echo "$file" | sed -E 's/.*from\s+["'"'"']([^"'"'"']+)["'"'"'];/\1/')
          echo "Ruta extraída: $path"

          if [[ "$path" == .* || "$path" == ..* ]]; then
            resolved_path=$(realpath --relative-to=. "$(dirname "$TEST_POSIX")/$path")
          elif [[ "$path" == @* ]]; then
            alias_name=$(echo "$path" | cut -d'/' -f1)
            alias_subpath=$(echo "$path" | sed -E 's|^[^/]+/?||')
            resolved_path="${!alias_name}/$alias_subpath"
          else
            resolved_path="$path"
          fi

          echo "Ruta resuelta: $resolved_path"

          if [[ "$resolved_path" == cypress/* ]]; then
            RESOLVED_FILES+="$resolved_path"$'\n'
          fi
        done <<< "$FILE_REFERENCES"

        echo "Archivos resueltos: $RESOLVED_FILES"
        JSON_OUTPUT=$(echo "$RESOLVED_FILES" | sort | uniq | jq -Rn --arg source "$TEST_POSIX" '{source: $source, files: [inputs | split("\n") | map(select(length > 0))]}')
        echo "$JSON_OUTPUT" #> extracted_files.json

