name: Extract File References

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Ruta del archivo de prueba'
        required: true
        default: 'cypress/e2e/Tests/API/Cards/GX3-5811-boardMembers.api.cy.ts'

jobs:
  extract-references:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Step 1 - Read aliases from .aliases.json
      run: |
        echo "Leyendo los alias desde .aliases.json"
        ALIAS_JSON=$(cat .aliases.json)
        echo "$ALIAS_JSON" | grep -o '"@[^"]*":\s*"[^"]*"' | awk -F ': ' '{print $1, $2}' > alias_list.txt
        echo "Alias leídos y almacenados en alias_list.txt"
        echo ""
        echo "Contenido inicial de alias_list.txt:"
        cat alias_list.txt
        echo ""
        
    - name: Step 2 - Extract import statements
      run: |
        echo "Leyendo las referencias de importación desde el archivo: ${{ github.event.inputs.test_file }}"
        FILE_REFERENCES=$(grep -Eo 'import\s+.*\s+from\s+["'"'"'][^"'"'"']+["'"'"'];' "${{ github.event.inputs.test_file }}" || echo "")
        echo "Referencias encontradas:"
        echo "$FILE_REFERENCES"
        echo ""
        
    - name: Step 3 - Process and resolve paths iteratively
      run: |
        echo "Iniciando la resolución de rutas..."
        > resolved_files.txt
        > temp_resolved_files.txt
        # Añadir la ruta inicial al archivo resolved_files.txt
        echo "${{ github.event.inputs.test_file }}" >> resolved_files.txt
        echo "${{ github.event.inputs.test_file }}" >> temp_resolved_files.txt
        while true; do
          # Leer el primer archivo de temp_resolved_files.txt
          current_file=$(head -n 1 temp_resolved_files.txt)
          if [[ -z "$current_file" ]]; then
            echo "No hay más archivos que procesar, saliendo..."
            break
          fi
          echo "Leyendo archivo actual: $current_file"
          
          # Eliminar el archivo leído de temp_resolved_files.txt
          sed -i '1d' temp_resolved_files.txt
          
          # Leer referencias de importación
          FILE_REFERENCES=$(grep -Eo 'import\s+.*\s+from\s+["'"'"'][^"'"'"']+["'"'"'];' "$current_file" || echo "")
          echo "Referencias encontradas en $current_file:"
          echo "$FILE_REFERENCES"
          echo ""
          while IFS= read -r file; do
            path=$(echo "$file" | sed -E 's/.*from\s+["'"'"']([^"'"'"']+)["'"'"'];/\1/')
            resolved_path=""
            # Resolver rutas relativas
            if [[ "$path" == .* || "$path" == ..* ]]; then
              resolved_path=$(realpath --relative-to=. "$(dirname "$current_file")/$path")
            fi
            # Resolver alias
            if [[ "$path" == @* ]]; then
              alias_name=$(echo "$path" | cut -d'/' -f1)
              alias_subpath=$(echo "$path" | sed -E 's|^[^/]+/?||')
              alias_base=$(grep -o "\"$alias_name\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" .aliases.json | awk -F ': ' '{print $2}' | tr -d '"')
              resolved_path="${alias_base}/$alias_subpath"
            fi
            # Añadir extensión si falta
            if [[ "$resolved_path" != *.js && "$resolved_path" != *.ts ]]; then
              if [[ -f "${resolved_path}.js" ]]; then
                resolved_path="${resolved_path}.js"
              elif [[ -f "${resolved_path}.ts" ]]; then
                resolved_path="${resolved_path}.ts"
              fi
            fi
            # Eliminar './' al principio de la ruta
            resolved_path="${resolved_path#./}"
            # Filtrar y mostrar solo las rutas relevantes
            if [[ "$resolved_path" == cypress/* ]]; then
              echo "Archivo relevante encontrado: $resolved_path"
              if ! grep -qx "$resolved_path" resolved_files.txt; then
                echo "$resolved_path" >> resolved_files.txt
                echo "$resolved_path" >> temp_resolved_files.txt
              fi
            fi
          done <<< "$FILE_REFERENCES"
          echo "Contenido actual de resolved_files.txt:"
          cat resolved_files.txt
          echo ""
          echo "Contenido actual de temp_resolved_files.txt:"
          cat temp_resolved_files.txt
          echo ""
        done
        echo "Resolución de rutas completa."
        echo "Contenido final de resolved_files.txt:"
        cat resolved_files.txt
        echo ""
    - name: Buscar sentencias 'cy.fixture' y extraer rutas
      run: |
        echo "Buscando sentencias 'cy.fixture' en los archivos relevantes..."
        while IFS= read -r resolved_file; do
          echo "Analizando archivo: $resolved_file"
          # Buscar y extraer la ruta entre paréntesis de 'cy.fixture'
          while IFS= read -r cy_fixture_line; do
            # Asegurarnos de que estamos buscando solo la sentencia cy.fixture
            if [[ "$cy_fixture_line" =~ cy\.fixture["'"'"']([^"'"'"']+)["'"'"'] ]]; then
              echo "    Línea de cy.fixture encontrada: $cy_fixture_line"
              echo "    Ruta extraída: ${BASH_REMATCH[1]}"
            else
              echo "    No se extrajo una ruta válida."
            fi
          done < <(grep -Eo 'cy\.fixture(["'"'"'][^"'"'"']+["'"'"'])' "$resolved_file")
        done < resolved_files.txt
    - name: Show resolved files content
      run: |
        echo "Mostrando contenido final de resolved_files.txt:"
        cat resolved_files.txt

